import React from 'react'
import Head from 'next/Head';
import Header from './Header';

export default function Layout({ title, children }) {


    return (
        <div className='min-h-screen bg-gray-300'>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header title={title} ></Header>
            <main className='container w-8/12 mx-auto'>
                {children}
            </main>
        </div>
    )
}
